CREATE TABLE GESTAO.VTX_USR (
    ID_USR BIGINT AUTO_INCREMENT PRIMARY KEY,
    NM_USR VARCHAR(255) NOT NULL,
    EMAIL_USR VARCHAR(255) NOT NULL UNIQUE,
    SENHA_USR VARCHAR(255) NOT NULL,
    DOC_USR VARCHAR(14) NOT NULL UNIQUE,
    DT_NASC_USR DATE NOT NULL,
    DT_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DT_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX IDX_VTX_USR_NM ON GESTAO.VTX_USR (NM_USR);
