ALTER TABLE GESTAO.VTX_USR DROP INDEX DOC_USR;

ALTER TABLE GESTAO.VTX_USR
    MODIFY COLUMN DOC_USR VARBINARY(255) NOT NULL;

ALTER TABLE GESTAO.VTX_USR
    ADD COLUMN DOC_IV VARBINARY(16) NOT NULL AFTER DOC_USR;

ALTER TABLE GESTAO.VTX_USR
    ADD COLUMN DOC_HASH VARBINARY(32) NOT NULL AFTER DOC_IV;
ALTER TABLE GESTAO.VTX_USR
    ADD CONSTRAINT UQ_VTX_USR_DOC_HASH UNIQUE (DOC_HASH);

CREATE FUNCTION GESTAO.FN_CRIPTOGRAFA_DOC(
    p_texto VARCHAR(255),
    p_chave VARBINARY(64),
    p_iv    VARBINARY(16)
) RETURNS VARBINARY(255)
    DETERMINISTIC
    NO SQL
    SQL SECURITY INVOKER
    RETURN AES_ENCRYPT(p_texto, p_chave, p_iv);

CREATE FUNCTION GESTAO.FN_DESCRIPTOGRAFA_DOC(
    p_cifra VARBINARY(255),
    p_chave VARBINARY(64),
    p_iv    VARBINARY(16)
) RETURNS VARCHAR(255)
    DETERMINISTIC
    NO SQL
    SQL SECURITY INVOKER
    RETURN CAST(AES_DECRYPT(p_cifra, p_chave, p_iv) AS CHAR);

CREATE FUNCTION GESTAO.FN_INDICE_CEGO_DOC(
    p_texto VARCHAR(255),
    p_chave VARCHAR(64)
) RETURNS VARBINARY(32)
    DETERMINISTIC
    NO SQL
    SQL SECURITY INVOKER
    RETURN UNHEX(SHA2(CONCAT(p_chave, p_texto), 256));